### GET ALL
GET http://localhost:3000/product
### CREATE
POST http://localhost:3000/product
Content-Type: application/json

{
  "name": "Product 2",
  "price": 100,
  "categoryId": 1
}
### GET ONE
GET http://localhost:3000/product/3
### DELETE
DELETE http://localhost:3000/product/1
###