GET http://localhost:3000/product
###
POST http://localhost:3000/product
Content-Type: application/json

{
  "name": "Product 2",
  "price": 100,
  "categoryId": 1
}
###
GET http://localhost:3000/product/3
###